# This is a basic CipherCaller configuration file.
#
# "Default" values refer to values assumed by the program if the relevant key is missing from the configuration file.
# For further guidance, please visit the project wiki https://github.com/Tombuster/CipherCaller/wiki

input:
  method: file  # Specify from [microphone, file] operation mode. Default value is "file"
  file_path: media/input/example.wav  # Input file path for "file" mode

output:
  method: file  # Specify from [file, playback, both]. Default value is "file"
  file_path: media/output/example.wav  # Output file path for "file" and "both" modes

pyaudio:  # Microphone input parameters
  chunk_size: 241  # This is also the transmission datagram's data field length <- not rlly
  channels: 1
  rate: 44100

sockets:
  receiver_host: receiver  # Docker SERVICE name. Change to IPv4 address for remote deployment
  # receiver_address:  # Address supplied to receiver's socket.bind() command; Default is ""
  port: 2004
  sender_delay_ms: 3000  # Delay before streaming starts, used to let receiver socket bind
  receiver_timeout_ms: 10000  # Denotes the delay between receiving a datagram and breaking the receiving loop. Must exceed sender startup time

logging:
  level: INFO

plugin:
  # Plugin configuration
  # When creating your own plugin, you can include its keys in this section
  use_plugin: no  # Specify from [yes, no]. Default value is "no"
  name: example  # Name of Python file containing desired plugin. MUST be in the src/plugins/ directory!