# CipherCaller docker configuration
# Version: default
# Last modified: 2026-07-21


services:
    sender:
        build:
            context: ./
            dockerfile: ./src/Dockerfile  # ./src/sender/Dockerfile
        container_name: ciphercaller-sender
        environment:
            - ROLE=sender
        volumes:
            - ./config.yaml:/ciphercaller/config.yaml:ro
            - ./media:/ciphercaller/media:ro
        networks:
            - transmission_net
        depends_on:
            - receiver
    # === FOR MICROPHONE INPUT === #
        devices:
            - /dev/snd:/sound:ro
        group_add:
            - audio
        # Sender hardware limits:
        # cpus: 0.5

    receiver:
        build:
            context: ./
            dockerfile: ./src/Dockerfile
        container_name: ciphercaller-receiver
        environment:
            - ROLE=receiver
        volumes:
            - ./config.yaml:/ciphercaller/config.yaml:ro
            - ./media:/ciphercaller/media:wo
        networks:
            - transmission_net
    # === FOR LIVE SPEAKER OUTPUT === #
        devices:
            - /dev/snd:/sound:wo
        group_add:
            - audio
        # ports:
        #     - "2004:2004"  # Only needed for remote deployments
        # Receiver hardware limits:
        # cpus: 0.5

networks:
    transmission_net:
        driver: bridge